package dev.tinymcserver.app.core.storage

import dev.tinymcserver.app.core.model.InstanceConfig
import java.io.File
import java.util.LinkedHashMap

/** server.properties 读写（保留未知键，顺序稳定） */
object ServerProperties {

    /** 常见键 → 中文名（用于「服务器属性」页，避免满屏英文看不懂） */
    private val LABELS = mapOf(
        "accepts-transfers" to "接受跨服转移",
        "allow-flight" to "允许飞行",
        "allow-nether" to "允许下界",
        "broadcast-console-to-ops" to "广播控制台到 OP",
        "broadcast-rcon-to-ops" to "广播 RCON 到 OP",
        "difficulty" to "难度",
        "enable-command-block" to "启用命令方块",
        "enable-jmx-monitoring" to "启用 JMX 监控",
        "enable-query" to "启用 Query 协议",
        "enable-rcon" to "启用 RCON",
        "enable-status" to "服务器列表显示状态",
        "enforce-secure-profile" to "强制安全聊天签名",
        "enforce-whitelist" to "白名单强制执行",
        "entity-broadcast-range-percentage" to "实体广播范围(%)",
        "force-gamemode" to "强制默认游戏模式",
        "function-permission-level" to "函数权限等级",
        "gamemode" to "默认游戏模式",
        "generate-structures" to "生成结构",
        "generator-settings" to "自定义生成设置",
        "hardcore" to "极限模式",
        "hide-online-players" to "隐藏在线玩家",
        "initial-disabled-packs" to "初始禁用的数据包",
        "initial-enabled-packs" to "初始启用的数据包",
        "level-name" to "世界名称",
        "level-seed" to "世界种子",
        "level-type" to "世界类型",
        "log-ips" to "记录玩家 IP",
        "max-chained-neighbor-updates" to "连锁更新上限",
        "max-players" to "最大玩家数",
        "max-tick-time" to "单 tick 超时(毫秒)",
        "max-world-size" to "世界边界最大半径",
        "motd" to "服务器标语 MOTD",
        "network-compression-threshold" to "网络压缩阈值",
        "online-mode" to "正版验证",
        "op-permission-level" to "OP 权限等级",
        "player-idle-timeout" to "挂机踢出(分钟)",
        "prevent-proxy-connections" to "阻止代理连接",
        "pvp" to "允许玩家对战",
        "query.port" to "Query 端口",
        "rate-limit" to "数据包限流",
        "rcon.password" to "RCON 密码",
        "rcon.port" to "RCON 端口",
        "region-file-compression" to "区域文件压缩算法",
        "require-resource-pack" to "强制资源包",
        "resource-pack" to "资源包下载地址",
        "resource-pack-id" to "资源包 ID",
        "resource-pack-prompt" to "资源包提示文本",
        "resource-pack-sha1" to "资源包 SHA1",
        "server-ip" to "监听地址",
        "server-port" to "服务器端口",
        "simulation-distance" to "模拟距离",
        "spawn-animals" to "生成动物",
        "spawn-monsters" to "生成怪物",
        "spawn-npcs" to "生成村民",
        "spawn-protection" to "出生点保护半径",
        "sync-chunk-writes" to "同步写入区块",
        "text-filtering-config" to "聊天过滤配置",
        "text-filtering-version" to "聊天过滤版本",
        "use-native-transport" to "使用 Linux 原生传输",
        "view-distance" to "视距",
        "white-list" to "启用白名单",
    )

    /** 键的中文名；没有映射时返回原键 */
    fun displayName(key: String): String = LABELS[key] ?: key

    /** 键的通用说明（常见取值），没有则返回 null */
    fun hint(key: String): String? = when (key) {
        "difficulty" -> "peaceful / easy / normal / hard"
        "gamemode" -> "survival / creative / adventure / spectator"
        "online-mode" -> "true = 仅正版可进；false = 允许离线（局域网友好，公网易被冒充）"
        "white-list" -> "true / false，配合 whitelist.json"
        "level-type" -> "minecraft:normal / flat / large_biomes / amplified"
        else -> null
    }

    fun parse(text: String): LinkedHashMap<String, String> {
        val map = LinkedHashMap<String, String>()
        text.lineSequence().forEach { line ->
            val t = line.trim()
            if (t.isEmpty() || t.startsWith("#")) return@forEach
            val i = t.indexOf('=')
            if (i > 0) map[t.substring(0, i).trim()] = t.substring(i + 1).trim()
        }
        return map
    }

    fun serialize(map: Map<String, String>): String = buildString {
        append("#Minecraft server properties\n")
        append("#Generated by Tiny MC Server\n")
        map.forEach { (k, v) -> append(k).append('=').append(v).append('\n') }
    }

    fun read(file: File): String = if (file.exists()) file.readText() else ""

    fun write(file: File, map: Map<String, String>) {
        file.parentFile?.mkdirs()
        file.writeText(serialize(map))
    }

    /** 将创建向导配置写入 server.properties（保留已有其它键） */
    fun applyConfig(file: File, cfg: InstanceConfig) {
        val map = if (file.exists()) parse(file.readText()) else LinkedHashMap()
        map["server-port"] = cfg.port.toString()
        map["online-mode"] = cfg.onlineMode.toString()
        map["difficulty"] = cfg.difficulty
        map["view-distance"] = cfg.viewDistance.toString()
        map["simulation-distance"] = cfg.simulationDistance.toString()
        map["max-players"] = cfg.maxPlayers.toString()
        map["white-list"] = cfg.whitelist.toString()
        map["motd"] = cfg.motd
        if (!map.containsKey("level-name")) map["level-name"] = "world"
        if (!map.containsKey("enable-command-block")) map["enable-command-block"] = "true"
        if (!map.containsKey("spawn-protection")) map["spawn-protection"] = "16"
        if (!map.containsKey("gamemode")) map["gamemode"] = "survival"
        write(file, map)
    }
}

/** EULA 处理 */
object EulaManager {
    fun isAccepted(dir: File): Boolean {
        val f = File(dir, "eula.txt")
        if (!f.exists()) return false
        return f.readText().lineSequence().any {
            it.trim().equals("eula=true", ignoreCase = true)
        }
    }

    fun accept(dir: File) {
        File(dir, "eula.txt").writeText(
            "#Tiny MC Server 已获用户授权生成\n" +
                "#https://aka.ms/MinecraftEULA\n" +
                "eula=true\n"
        )
    }
}
